### ISSUE TITLE
intellij idea 调试unity出错 。    昨天还好好的，今天一AttachProcess就报错。 然后更新了插件。能Attach，但调试不了。下面是log

### ISSUE THREAD

**Issue by dcl-Cheng** [EmmyLua/IntelliJ-EmmyLua#113]
LOG_WARNING_OUTPUT
java.lang.NoSuchFieldError: LOG_WARNING_OUTPUT
	at com.tang.intellij.lua.debugger.attach.DMMessage.print(LuaAttachMessages.kt:183)
	at com.tang.intellij.lua.debugger.attach.LuaAttachDebugProcessBase.handle(LuaAttachDebugProcessBase.kt:143)
	at com.tang.intellij.lua.debugger.attach.LuaAttachBridgeBase.handleMessage(LuaAttachBridgeBase.kt:92)
	at com.tang.intellij.lua.debugger.attach.LuaAttachBridgeBase.handleMsg(LuaAttachBridgeBase.kt:142)
	at com.tang.intellij.lua.debugger.attach.LuaAttachBridgeBase.processPack(LuaAttachBridgeBase.kt:130)
	at com.tang.intellij.lua.debugger.attach.LuaAttachBridgeBase.access$processPack(LuaAttachBridgeBase.kt:37)
	at com.tang.intellij.lua.debugger.attach.LuaAttachBridgeBase$connect$1.run(LuaAttachBridgeBase.kt:113)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by tangzx** [comment]
你用的IDEA是什么版本？昨天好的今天有没有作升级什么的操作？

**Comment by dcl-Cheng** [comment]
idea版本是2017.1.13 。  其他的没任何升级，除了第二天看不行升级了emmylua1.22版本。同样的项目，同样的操作。试了unity4.6和unity5.6版本。都不行，排除unity问题。

**Comment by tangzx** [comment]
升级IDEA到3.x试试

**Comment by dcl-Cheng** [comment]
升级到3.4  可调试了。    谢谢！    
这是什么问题啊，原idea和lua的版本都没升级的情况下应该没问题才对啊

**Comment by tangzx** [comment]
低版本有一些兼容问题未处理
