### ISSUE TITLE
写for循环的时候抛异常

### ISSUE THREAD

**Issue by fcloveclm** [EmmyLua/IntelliJ-EmmyLua#130]
1. 当时在写for循环，使用 vim插件写得比较快，无法复现
1. 可能是cfg声明的时候有问题
1. Emmylua版本：1.2.3，Idea版本：2018.1
1. 具体堆栈

```
for , value 
 parent=
        for , value in pairs(cfg.condition) do
            
        end
    
java.lang.Throwable: for , value 
 parent=
        for , value in pairs(cfg.condition) do
            
        end
    
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.intellij.psi.impl.PsiElementBase.notNullChild(PsiElementBase.java:285)
	at com.tang.intellij.lua.psi.impl.LuaForAStatImpl.getParamNameDef(LuaForAStatImpl.java:37)
	at com.tang.intellij.lua.psi.LuaPsiTreeUtilEx.walkUpPsiLocalName(LuaPsiTreeUtilEx.kt:131)
	at com.tang.intellij.lua.psi.LuaPsiTreeUtilEx.walkUpNameDef(LuaPsiTreeUtilEx.kt:91)
	at com.tang.intellij.lua.psi.LuaPsiResolveUtilKt.resolveInFile(LuaPsiResolveUtil.kt:69)
	at com.tang.intellij.lua.psi.LuaPsiResolveUtilKt.resolve(LuaPsiResolveUtil.kt:132)
	at com.tang.intellij.lua.annotator.LuaAnnotator$LuaElementVisitor.visitNameExpr(LuaAnnotator.kt:142)
	at com.tang.intellij.lua.psi.impl.LuaNameExprImpl.accept(LuaNameExprImpl.java:34)
	at com.tang.intellij.lua.psi.impl.LuaNameExprImpl.accept(LuaNameExprImpl.java:38)
	at com.tang.intellij.lua.annotator.LuaAnnotator.annotate(LuaAnnotator.kt:52)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:139)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:371)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:303)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:330)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:333)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:333)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:300)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:239)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by tangzx** [comment]
想起来了，已经改掉了，下个版本应该没有了。
