### ISSUE TITLE
Outdated stub in index

### ISSUE THREAD

**Issue by cmingjian** [EmmyLua/IntelliJ-EmmyLua#153]
弹了个Fatal Error的对话框，报错详情：
`Outdated stub in index: file:///home/cmj/ttlz2/service/worldboss/worldboss.lua indexed at 1526114314126 with document size 72834, doc=null, docSaved=true, wasIndexedAlready=false, queried at 1527229872391
indexed lengths={chars=72834, bytes=76980}
doc length=-1
file length=61578
cached PSI class com.tang.intellij.lua.psi.LuaPsiFile
projects with file: 1
java.lang.Exception
	at com.intellij.psi.stubs.StubTreeLoaderImpl.a(StubTreeLoaderImpl.java:175)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.a(StubTreeLoaderImpl.java:145)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:113)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readOrBuild(StubTreeLoaderImpl.java:53)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:651)
	at com.intellij.psi.impl.source.PsiFileImpl.getStub(PsiFileImpl.java:614)
	at com.tang.intellij.lua.psi.LuaPsiFile.getModuleName(LuaPsiFile.kt:52)
	at com.tang.intellij.lua.ty.DeclarationsKt$inferFile$1.compute(Declarations.kt:185)
	at com.tang.intellij.lua.ty.DeclarationsKt$inferFile$1.compute(Declarations.kt)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:67)
	at com.tang.intellij.lua.ext.UtilsKt.recursionGuard(utils.kt:23)
	at com.tang.intellij.lua.ext.UtilsKt.recursionGuard$default(utils.kt:22)
	at com.tang.intellij.lua.ty.DeclarationsKt.inferFile(Declarations.kt:184)
	at com.tang.intellij.lua.ty.DeclarationsKt.inferInner(Declarations.kt:47)
	at com.tang.intellij.lua.ty.LuaTypeInfer.inferType(LuaTypeInfer.kt:25)
	at com.tang.intellij.lua.ext.ILuaTypeInfer$Companion.infer(ILuaTypeInfer.kt:33)
	at com.tang.intellij.lua.ty.DeclarationsKt.infer(Declarations.kt:36)
	at com.tang.intellij.lua.psi.LuaTypeGuessable.guessType(LuaTypeGuessable.java:29)
	at com.tang.intellij.lua.ty.ExpressionsKt.infer(Expressions.kt:160)
	at com.tang.intellij.lua.ty.ExpressionsKt.inferExpr(Expressions.kt:36)
	at com.tang.intellij.lua.ty.DeclarationsKt.inferInner(Declarations.kt:42)
	at com.tang.intellij.lua.ty.LuaTypeInfer.inferType(LuaTypeInfer.kt:25)
	at com.tang.intellij.lua.ext.ILuaTypeInfer$Companion.infer(ILuaTypeInfer.kt:33)
	at com.tang.intellij.lua.ty.DeclarationsKt.infer(Declarations.kt:36)
	at com.tang.intellij.lua.psi.LuaTypeGuessable.guessType(LuaTypeGuessable.java:29)
	at com.tang.intellij.lua.psi.LuaPsiImplUtilKt$guessTypeAt$1.invoke(LuaPsiImplUtil.kt:275)
	at com.tang.intellij.lua.psi.LuaPsiImplUtilKt$guessTypeAt$1.invoke(LuaPsiImplUtil.kt)
	at com.tang.intellij.lua.search.SearchContext.withIndex(SearchContext.kt:44)
	at com.tang.intellij.lua.psi.LuaPsiImplUtilKt.guessTypeAt(LuaPsiImplUtil.kt:275)
	at com.tang.intellij.lua.psi.impl.LuaExprListImpl.guessTypeAt(LuaExprListImpl.java:50)
	at com.tang.intellij.lua.ty.DeclarationsKt$infer$1.invoke(Declarations.kt:140)
	at com.tang.intellij.lua.ty.DeclarationsKt$infer$1.invoke(Declarations.kt)
	at com.tang.intellij.lua.search.SearchContext.withIndex(SearchContext.kt:44)
	at com.tang.intellij.lua.ty.DeclarationsKt.infer(Declarations.kt:139)
	at com.tang.intellij.lua.ty.DeclarationsKt.inferInner(Declarations.kt:44)
	at com.tang.intellij.lua.ty.LuaTypeInfer.inferType(LuaTypeInfer.kt:25)
	at com.tang.intellij.lua.ext.ILuaTypeInfer$Companion.infer(ILuaTypeInfer.kt:33)
	at com.tang.intellij.lua.ty.DeclarationsKt.infer(Declarations.kt:36)
	at com.tang.intellij.lua.psi.LuaTypeGuessable.guessType(LuaTypeGuessable.java:29)
	at com.tang.intellij.lua.ty.ExpressionsKt.getType(Expressions.kt:271)
	at com.tang.intellij.lua.ty.ExpressionsKt.access$getType(Expressions.kt:1)
	at com.tang.intellij.lua.ty.ExpressionsKt$infer$set$1.compute(Expressions.kt:206)
	at com.tang.intellij.lua.ty.ExpressionsKt$infer$set$1.compute(Expressions.kt)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:67)
	at com.tang.intellij.lua.ext.UtilsKt.recursionGuard(utils.kt:23)
	at com.tang.intellij.lua.ext.UtilsKt.recursionGuard$default(utils.kt:22)
	at com.tang.intellij.lua.ty.ExpressionsKt.infer(Expressions.kt:202)
	at com.tang.intellij.lua.ty.ExpressionsKt.inferExpr(Expressions.kt:40)
	at com.tang.intellij.lua.ty.DeclarationsKt.inferInner(Declarations.kt:42)
	at com.tang.intellij.lua.ty.LuaTypeInfer.inferType(LuaTypeInfer.kt:25)
	at com.tang.intellij.lua.ext.ILuaTypeInfer$Companion.infer(ILuaTypeInfer.kt:33)
	at com.tang.intellij.lua.ty.DeclarationsKt.infer(Declarations.kt:36)
	at com.tang.intellij.lua.psi.LuaTypeGuessable.guessType(LuaTypeGuessable.java:29)
	at com.tang.intellij.lua.psi.LuaPsiImplUtilKt.guessParentType(LuaPsiImplUtil.kt:282)
	at com.tang.intellij.lua.psi.impl.LuaIndexExprImpl.guessParentType(LuaIndexExprImpl.java:86)
	at com.tang.intellij.lua.stubs.LuaIndexExprType.createStub(LuaIndexExprStub.kt:65)
	at com.tang.intellij.lua.stubs.LuaIndexExprType.createStub(LuaIndexExprStub.kt:40)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.a(DefaultStubBuilder.java:113)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.visitNode(DefaultStubBuilder.java:88)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.buildStubTree(DefaultStubBuilder.java:83)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTreeFor(DefaultStubBuilder.java:58)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTree(DefaultStubBuilder.java:39)
	at com.tang.intellij.lua.stubs.LuaFileElementType$getBuilder$1.buildStubTree(LuaFileStub.kt:68)
	at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:84)
	at com.intellij.psi.stubs.StubUpdatingIndex$3.a(StubUpdatingIndex.java:232)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:907)
	at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:214)
	at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:197)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:271)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.calculateUpdateData(VfsAwareMapReduceIndex.java:99)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:214)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1645)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1581)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:511)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1540)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1528)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1507)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1663)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1660)
	at com.intellij.util.indexing.UpdateTask.a(UpdateTask.java:76)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:46)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1682)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:725)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:691)
	at com.intellij.psi.stubs.StubIndexImpl.a(StubIndexImpl.java:346)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:323)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:145)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134)
	at com.tang.intellij.lua.stubs.index.LuaClassMemberIndex.get(LuaClassMemberIndex.kt:37)
	at com.tang.intellij.lua.stubs.index.LuaClassMemberIndex$Companion.process(LuaClassMemberIndex.kt:45)
	at com.tang.intellij.lua.stubs.index.LuaClassMemberIndex$Companion.process(LuaClassMemberIndex.kt:51)
	at com.tang.intellij.lua.stubs.index.LuaClassMemberIndex$Companion.process$default(LuaClassMemberIndex.kt:49)
	at com.tang.intellij.lua.stubs.index.LuaClassMemberIndex$Companion.processAll(LuaClassMemberIndex.kt:103)
	at com.tang.intellij.lua.stubs.index.LuaClassMemberIndex$Companion.find(LuaClassMemberIndex.kt:80)
	at com.tang.intellij.lua.ty.TyClass.findMember(TyClass.kt:116)
	at com.tang.intellij.lua.psi.LuaPsiResolveUtilKt$resolve$2.process(LuaPsiResolveUtil.kt:184)
	at com.tang.intellij.lua.psi.LuaPsiResolveUtilKt$resolve$2.process(LuaPsiResolveUtil.kt)
	at com.tang.intellij.lua.ty.Ty.eachTopClass(Ty.kt:161)
	at com.tang.intellij.lua.psi.LuaPsiResolveUtilKt.resolve(LuaPsiResolveUtil.kt:183)
	at com.tang.intellij.lua.psi.LuaPsiResolveUtilKt.resolve(LuaPsiResolveUtil.kt:177)
	at com.tang.intellij.lua.reference.LuaIndexReference.resolve(LuaIndexReference.kt:56)
	at com.tang.intellij.lua.reference.LuaIndexReference.resolve(LuaIndexReference.kt:52)
	at com.tang.intellij.lua.codeInsight.LuaLineMarkerProvider.collectNavigationMarkers(LuaLineMarkerProvider.kt:149)
	at com.tang.intellij.lua.codeInsight.LuaLineMarkerProvider.collectSlowLineMarkers(LuaLineMarkerProvider.kt:196)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:213)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:112)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:96)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:107)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:534)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:479)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:229)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)`

**Comment by tangzx** [comment]
暂时不能解决，未找到原因
