### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by cs1999** [EmmyLua/IntelliJ-EmmyLua#172]
null
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742)
	at com.intellij.util.containers.ContainerUtil.process(ContainerUtil.java:788)
	at com.tang.intellij.lua.ty.Ty.eachTopClass(Ty.kt:163)
	at com.tang.intellij.lua.ty.ExpressionsKt$infer$retTy$1.compute(Expressions.kt:329)
	at com.tang.intellij.lua.ty.ExpressionsKt$infer$retTy$1.compute(Expressions.kt)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:67)
	at com.tang.intellij.lua.ext.UtilsKt.recursionGuard(utils.kt:23)
	at com.tang.intellij.lua.ext.UtilsKt.recursionGuard$default(utils.kt:22)
	at com.tang.intellij.lua.ty.ExpressionsKt.infer(Expressions.kt:293)
	at com.tang.intellij.lua.ty.ExpressionsKt.inferExpr(Expressions.kt:42)
	at com.tang.intellij.lua.ty.DeclarationsKt.inferInner(Declarations.kt:42)
	at com.tang.intellij.lua.ty.LuaTypeInfer.inferType(LuaTypeInfer.kt:25)
	at com.tang.intellij.lua.ext.ILuaTypeInfer$Companion.infer(ILuaTypeInfer.kt:33)
	at com.tang.intellij.lua.ty.DeclarationsKt.infer(Declarations.kt:36)
	at com.tang.intellij.lua.psi.LuaTypeGuessable.guessType(LuaTypeGuessable.java:29)
	at com.tang.intellij.lua.psi.LuaPsiImplUtilKt.guessParentType(LuaPsiImplUtil.kt:191)
	at com.tang.intellij.lua.psi.impl.LuaCallExprImpl.guessParentType(LuaCallExprImpl.java:56)
	at com.tang.intellij.lua.codeInsight.LuaParameterHintsProvider.getParameterHints(LuaParameterHintsProvider.kt:67)
	at com.intellij.codeInsight.hints.ParameterHintsPass.process(ParameterHintsPass.java:84)
	at com.intellij.codeInsight.hints.ParameterHintsPass.lambda$doCollectInformation$0(ParameterHintsPass.java:76)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.intellij.codeInsight.hints.ParameterHintsPass.doCollectInformation(ParameterHintsPass.java:76)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by tangzx** [comment]
这个错误应该不存在了，你的版本太旧，去群里下载最新版本
