### ISSUE TITLE
lua文件不能进行编辑，有报错堆栈

### ISSUE THREAD

**Issue by mujl** [EmmyLua/IntelliJ-EmmyLua#330]
Environment（环境）
--------------
   name EmmyLua  |   version  1.3.1.136-IDEA182
----------|----------
 IDEA version  idea 2019.3.1       | [e.g. IC2018.2 EAP, CL2018.1.2]
 EmmyLua version1.3.1.136-IDEA182  | [e.g. v1.2.5]
 OS    windows 10                    | [e.g. OSX 10.13.4, Windows 10]

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. …
2. …
3. …

What happens?（出现什么问题？）
-------------
exception in plugin emmylua 

What were you expecting to happen?（期望？）
-----------------------------------------
Normal operation without error reporting

Any logs, error output, etc?（有没有什么log, error输出？）
com.intellij.openapi.util.StackOverflowPreventedException: Endless recursion prevented
	at com.intellij.psi.impl.source.tree.FileElement.getStubbedSpine(FileElement.java:116)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:176)
	at com.intellij.psi.impl.source.FileTrees.withAst(FileTrees.java:149)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:213)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:712)
	at com.intellij.psi.impl.source.PsiFileImpl.getNode(PsiFileImpl.java:917)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:733)
	at com.tang.intellij.lua.psi.LuaRecursiveVisitor.visitElement(LuaRecursiveVisitor.kt:23)
	at com.tang.intellij.lua.psi.LuaDeclarationTreeBase.visitElementExt(LuaDeclarationTree.kt:349)
	at com.tang.intellij.lua.psi.LuaDeclarationTreeBase.visitElement(LuaDeclarationTree.kt:355)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:34)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
	at com.tang.intellij.lua.psi.LuaDeclarationTreeBase.buildTree(LuaDeclarationTree.kt:277)
	at com.tang.intellij.lua.psi.LuaDeclarationTree$Companion.get(LuaDeclarationTree.kt:47)
	at com.tang.intellij.lua.psi.LuaPsiResolveUtilKt.resolveInFile(LuaPsiResolveUtil.kt:37)
	at com.tang.intellij.lua.psi.LuaPsiResolveUtilKt.resolveLocal(LuaPsiResolveUtil.kt:31)
	at com.tang.intellij.lua.psi.LuaPsiResolveUtilKt.resolveLocal$default(LuaPsiResolveUtil.kt:30)
	at com.tang.intellij.lua.psi.PsiExtensionKt$forwardDeclaration$1.compute(PsiExtension.kt:450)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:148)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:64)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:147)
	at com.tang.intellij.lua.psi.PsiExtensionKt.getForwardDeclaration(PsiExtension.kt:448)
	at com.tang.intellij.lua.stubs.LuaFuncType.shouldCreateStub(LuaFuncStub.kt:68)
	at com.intellij.psi.impl.source.tree.FileElement$1.visitComposite(FileElement.java:136)
	at com.intellij.psi.impl.source.tree.CompositeElement.acceptTree(CompositeElement.java:130)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor$1.visit(RecursiveTreeElementWalkingVisitor.java:67)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor$1.visit(RecursiveTreeElementWalkingVisitor.java:59)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:65)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:52)
	at com.intellij.psi.impl.source.tree.RecursiveTreeElementWalkingVisitor.visitNode(RecursiveTreeElementWalkingVisitor.java:86)
	at com.intellij.psi.impl.source.tree.FileElement$1.visitComposite(FileElement.java:140)
	at com.intellij.psi.impl.source.tree.CompositeElement.acceptTree(CompositeElement.java:130)
	at com.intellij.psi.impl.source.tree.FileElement.calcStubbedDescendants(FileElement.java:127)
	at com.intellij.psi.impl.source.tree.FileElement.lambda$getStubbedSpine$0(FileElement.java:114)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.psi.impl.source.tree.FileElement.getStubbedSpine(FileElement.java:114)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:176)
	at com.intellij.psi.impl.source.FileTrees.withAst(FileTrees.java:149)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:213)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:712)
	at com.intellij.psi.impl.source.PsiFileImpl.getNode(PsiFileImpl.java:917)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:723)
	at com.intellij.psi.SyntaxTraverser$PsiApi.first(SyntaxTraverser.java:296)
	at com.intellij.psi.SyntaxTraverser$PsiApi.first(SyntaxTraverser.java:264)
	at com.intellij.psi.SyntaxTraverser$ApiEx.children(SyntaxTraverser.java:241)
	at com.intellij.psi.SyntaxTraverser$Api.fun(SyntaxTraverser.java:179)
	at com.intellij.psi.SyntaxTraverser$Api.fun(SyntaxTraverser.java:161)
	at com.intellij.util.containers.FilteredTraverserBase$Meta.childrenImpl(FilteredTraverserBase.java:427)
	at com.intellij.util.containers.FilteredTraverserBase$Meta.children(FilteredTraverserBase.java:413)
	at com.intellij.util.containers.FilteredTraverserBase.children(FilteredTraverserBase.java:294)
	at com.intellij.util.containers.TreeTraversal$P.iterable(TreeTraversal.java:725)
	at com.intellij.util.containers.TreeTraversal$P.iterator(TreeTraversal.java:719)
	at com.intellij.util.containers.TreeTraversal$BiOrderIt.nextImpl(TreeTraversal.java:460)
	at com.intellij.util.containers.JBIterator.peekNext(JBIterator.java:150)
	at com.intellij.util.containers.JBIterator.hasNext(JBIterator.java:110)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at com.intellij.codeInsight.hints.ParameterHintsPass.doCollectInformation(ParameterHintsPass.java:70)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:997)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:157)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?（其它说明）
------------------------
…

**Comment by leaveye** [comment]
same issue in version 1.3.6.224-IDEA213
