### ISSUE TITLE
SOE

### ISSUE THREAD

**Issue by batya239** [EmmyLua/IntelliJ-EmmyLua#353]
See https://youtrack.jetbrains.com/issue/IDEA-238943 for details and logs

[24271655]  ERROR - on.CompletionProgressIndicator - null 
java.lang.StackOverflowError
	at com.intellij.util.containers.ConcurrentIntKeyRefValueHashMap.get(ConcurrentIntKeyRefValueHashMap.java:95)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.getCachedDir(PersistentFSImpl.java:122)
	at com.intellij.openapi.vfs.newvfs.impl.VfsData.getFileById(VfsData.java:109)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.doFindChildById(VirtualDirectoryImpl.java:484)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$1ParentFinder.findChild(FSRecords.java:1119)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$1ParentFinder.findDescendantByIdPath(FSRecords.java:1112)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$1ParentFinder.access$2800(FSRecords.java:1076)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.findFileById(FSRecords.java:1130)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findFileById(PersistentFSImpl.java:1236)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findFileByIdIfCached(PersistentFSImpl.java:1241)
	at com.intellij.util.indexing.IndexInfrastructure.findFileByIdIfCached(IndexInfrastructure.java:110)
	at com.intellij.util.indexing.FileBasedIndexEx.lambda$processValuesInScope$6(FileBasedIndexEx.java:270)
	at com.intellij.util.indexing.FileBasedIndexEx.lambda$processValueIterator$7(FileBasedIndexEx.java:294)
	at com.intellij.util.indexing.FileBasedIndexEx.lambda$null$3(FileBasedIndexEx.java:215)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:231)
	at com.intellij.util.indexing.FileBasedIndexEx.lambda$processExceptions$4(FileBasedIndexEx.java:215)
	at com.intellij.util.indexing.IndexAccessValidator.validate(IndexAccessValidator.java:43)
	at com.intellij.util.indexing.FileBasedIndexEx.processExceptions(FileBasedIndexEx.java:215)
	at com.intellij.util.indexing.FileBasedIndexEx.processValueIterator(FileBasedIndexEx.java:293)
	at com.intellij.util.indexing.FileBasedIndexEx.processValuesInScope(FileBasedIndexEx.java:264)
	at com.intellij.util.indexing.FileBasedIndexEx.processValues(FileBasedIndexEx.java:186)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByName(FilenameIndex.java:186)
	at com.intellij.psi.search.FilenameIndex.processFilesByName(FilenameIndex.java:85)
	at com.intellij.psi.search.FilenameIndex.processFilesByName(FilenameIndex.java:72)
	at com.intellij.psi.search.FilenameIndex.getFilesByName(FilenameIndex.java:140)
	at com.intellij.psi.search.FilenameIndex.getFilesByName(FilenameIndex.java:63)
	at com.tang.intellij.lua.ext.LuaFileFuzzyResolver$find$1.run(LuaFileFuzzyResolver.kt:35)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:864)
	at com.tang.intellij.lua.ext.LuaFileFuzzyResolver.find(LuaFileFuzzyResolver.kt:32)
	at com.tang.intellij.lua.ext.ILuaFileResolver$Companion.findLuaFile(ILuaFileResolver.kt:29)
	at com.tang.intellij.lua.psi.LuaFileUtil.findFile(LuaFileUtil.kt:103)
	at com.tang.intellij.lua.psi.LuaPsiResolveUtilKt.resolveRequireFile(LuaPsiResolveUtil.kt:177)
	at com.tang.intellij.lua.ty.ExpressionsKt.infer(Expressions.kt:181)
	at com.tang.intellij.lua.ty.ExpressionsKt.inferExprInner(Expressions.kt:50)
	at com.tang.intellij.lua.ty.ExpressionsKt.inferExpr(Expressions.kt:43)
	at com.tang.intellij.lua.ty.DeclarationsKt.inferInner(Declarations.kt:41)
	at com.tang.intellij.lua.ty.LuaTypeInfer.inferType(LuaTypeInfer.kt:25)
	at com.tang.intellij.lua.ext.ILuaTypeInfer$Companion.infer(ILuaTypeInfer.kt:33)
	at com.tang.intellij.lua.search.SearchContext.inferAndCache(SearchContext.kt:175)
	at com.tang.intellij.lua.search.SearchContext.access$inferAndCache(SearchContext.kt:35)
	at com.tang.intellij.lua.search.SearchContext$Companion$infer$2.invoke(SearchContext.kt:58)
	at com.tang.intellij.lua.search.SearchContext$Companion$infer$2.invoke(SearchContext.kt:37)
	at com.tang.intellij.lua.search.SearchContext$Companion.with(SearchContext.kt:63)
	at com.tang.intellij.lua.search.SearchContext$Companion.infer(SearchContext.kt:58)
	at com.tang.intellij.lua.psi.LuaTypeGuessable.guessType(LuaTypeGuessable.java:29)
	at com.tang.intellij.lua.psi.LuaPsiImplUtilKt$guessTypeAt$1.invoke(LuaPsiImplUtil.kt:248)
	at com.tang.intellij.lua.psi.LuaPsiImplUtilKt$guessTypeAt$1.invoke(LuaPsiImplUtil.kt)
	at com.tang.intellij.lua.search.SearchContext.withIndex(SearchContext.kt:126)
	at com.tang.intellij.lua.psi.LuaPsiImplUtilKt.guessTypeAt(LuaPsiImplUtil.kt:248)
	at com.tang.intellij.lua.psi.impl.LuaExprListImpl.guessTypeAt(LuaExprListImpl.java:50)
	at com.tang.intellij.lua.ty.DeclarationsKt$infer$1.invoke(Declarations.kt:138)
	at com.tang.intellij.lua.ty.DeclarationsKt$infer$1.invoke(Declarations.kt)
	at com.tang.intellij.lua.search.SearchContext.withIndex(SearchContext.kt:126)
	at com.tang.intellij.lua.ty.DeclarationsKt.infer(Declarations.kt:137)
	at com.tang.intellij.lua.ty.DeclarationsKt.inferInner(Declarations.kt:43)
	at com.tang.intellij.lua.ty.LuaTypeInfer.inferType(LuaTypeInfer.kt:25)
	at com.tang.intellij.lua.ext.ILuaTypeInfer$Companion.infer(ILuaTypeInfer.kt:33)
	at com.tang.intellij.lua.search.SearchContext.inferAndCache(SearchContext.kt:175)
	at com.tang.intellij.lua.search.SearchContext.access$inferAndCache(SearchContext.kt:35)
	at com.tang.intellij.lua.search.SearchContext$Companion$infer$2.invoke(SearchContext.kt:58)
	at com.tang.intellij.lua.search.SearchContext$Companion$infer$2.invoke(SearchContext.kt:37)
	at com.tang.intellij.lua.search.SearchContext$Companion.with(SearchContext.kt:63)
	at com.tang.intellij.lua.search.SearchContext$Companion.infer(SearchContext.kt:58)
	at com.tang.intellij.lua.psi.LuaTypeGuessable.guessType(LuaTypeGuessable.java:29)
	at com.tang.intellij.lua.ty.ExpressionsKt.inferExpr(Expressions.kt:40)
	at com.tang.intellij.lua.ty.DeclarationsKt.inferInner(Declarations.kt:41)
	at com.tang.intellij.lua.ty.LuaTypeInfer.inferType(LuaTypeInfer.kt:25)
	at com.tang.intellij.lua.ext.ILuaTypeInfer$Companion.infer(ILuaTypeInfer.kt:33)
	at com.tang.intellij.lua.search.SearchContext.inferAndCache(SearchContext.kt:175)
	at com.tang.intellij.lua.search.SearchContext.access$inferAndCache(SearchContext.kt:35)
	at com.tang.intellij.lua.search.SearchContext$Companion$infer$2.invoke(SearchContext.kt:58)
	at com.tang.intellij.lua.search.SearchContext$Companion$infer$2.invoke(SearchContext.kt:37)
	at com.tang.intellij.lua.search.SearchContext$Companion.with(SearchContext.kt:63)
	at com.tang.intellij.lua.search.SearchContext$Companion.infer(SearchContext.kt:58)
	at com.tang.intellij.lua.psi.LuaTypeGuessable.guessType(LuaTypeGuessable.java:29)
	at com.tang.intellij.lua.psi.LuaPsiImplUtilKt.guessParentType(LuaPsiImplUtil.kt:255)
	at com.tang.intellij.lua.psi.impl.LuaIndexExprImpl.guessParentType(LuaIndexExprImpl.java:86)
	at com.tang.intellij.lua.ty.ExpressionsKt$infer$retTy$1.compute(Expressions.kt:361)
	at com.tang.intellij.lua.ty.ExpressionsKt$infer$retTy$1.compute(Expressions.kt)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:117)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:75)
	at com.tang.intellij.lua.ext.UtilsKt.recursionGuard(utils.kt:23)
	at com.tang.intellij.lua.ext.UtilsKt.recursionGuard$default(utils.kt:22)
	at com.tang.intellij.lua.ty.ExpressionsKt.infer(Expressions.kt:320)
	at com.tang.intellij.lua.ty.ExpressionsKt.inferExprInner(Expressions.kt:56)
	at com.tang.intellij.lua.ty.ExpressionsKt.inferExpr(Expressions.kt:43)
	at com.tang.intellij.lua.ty.DeclarationsKt.inferInner(Declarations.kt:41)
	at com.tang.intellij.lua.ty.LuaTypeInfer.inferType(LuaTypeInfer.kt:25)
	at com.tang.intellij.lua.ext.ILuaTypeInfer$Companion.infer(ILuaTypeInfer.kt:33)
	at com.tang.intellij.lua.search.SearchContext.inferAndCache(SearchContext.kt:175)
	at com.tang.intellij.lua.search.SearchContext.access$inferAndCache(SearchContext.kt:35)
	at com.tang.intellij.lua.search.SearchContext$Companion$infer$2.invoke(SearchContext.kt:58)
	at com.tang.intellij.lua.search.SearchContext$Companion$infer$2.invoke(SearchContext.kt:37)
	at com.tang.intellij.lua.search.SearchContext$Companion.with(SearchContext.kt:63)
	at com.tang.intellij.lua.search.SearchContext$Companion.infer(SearchContext.kt:58)
	at com.tang.intellij.lua.ty.DeclarationsKt.infer(Declarations.kt:35)
	at com.tang.intellij.lua.ty.ExpressionsKt.infer(Expressions.kt:189)

**Comment by tangzx** [comment]
The latest version 1.4.+ should be OK. The reason for this series of problems is the index mechanism problem, which cannot be solved because there is no solution before. Now the index system has finally been redesigned.
