### ISSUE TITLE
Rider2021.3安装Emmylua插件后无法使用

### ISSUE THREAD

**Issue by btkxx** [EmmyLua/IntelliJ-EmmyLua#447]
Rider2021.3 安装EmmyLua 1.3.6.220-IDEA213版本，打开设置EmmyLua界面一直Loading
![image](https://user-images.githubusercontent.com/17609953/147048450-50cb1d6e-b764-4db7-b939-bdaad9736609.png)

错误信息如下
···
Cannot create configurable

com.intellij.diagnostic.PluginException: Cannot create class com.tang.intellij.lua.project.LuaSettingsPanel (classloader=PluginClassLoader(plugin=PluginDescriptor(name=EmmyLua, id=com.tang, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\Rider2021.3\plugins\EmmyLua, version=1.3.6.220-IDEA213, package=null, isBundled=false), packagePrefix=null, instanceId=11, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:869)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:886)
	at com.intellij.openapi.options.ConfigurableEP$ClassProducer.createElement(ConfigurableEP.java:440)
	at com.intellij.openapi.options.ConfigurableEP.createConfigurable(ConfigurableEP.java:346)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.createConfigurable(ConfigurableWrapper.java:43)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getConfigurable(ConfigurableWrapper.java:119)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.cast(ConfigurableWrapper.java:92)
	at com.intellij.openapi.options.newEditor.SettingsTreeView.findConfigurableProject(SettingsTreeView.java:313)
	at com.intellij.openapi.options.newEditor.SettingsTreeView$MyRenderer.getTreeCellRendererComponent(SettingsTreeView.java:646)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(BasicTreeUI.java:3155)
	at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:493)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1344)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1465)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1272)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.ensurePathIsExpanded(VariableHeightLayoutCache.java:967)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.setExpandedState(VariableHeightLayoutCache.java:181)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.updateExpandedDescendants(BasicTreeUI.java:1975)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.treeExpanded(BasicTreeUI.java:4212)
	at java.desktop/javax.swing.JTree.fireTreeExpanded(JTree.java:2801)
	at java.desktop/javax.swing.JTree.setExpandedState(JTree.java:3652)
	at java.desktop/javax.swing.JTree.expandPath(JTree.java:2244)
	at com.intellij.ide.util.treeView.AbstractTreeUi$48.perform(AbstractTreeUi.java:3211)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:20)
	at com.intellij.ide.util.treeView.UpdaterTreeState.process(UpdaterTreeState.java:102)
	at com.intellij.ide.util.treeView.AbstractTreeUi.processInnerChange(AbstractTreeUi.java:3232)
	at com.intellij.ide.util.treeView.AbstractTreeUi.expandPath(AbstractTreeUi.java:3200)
	at com.intellij.ide.util.treeView.AbstractTreeUi.expand(AbstractTreeUi.java:1486)
	at com.intellij.ide.util.treeView.AbstractTreeUi.expand(AbstractTreeUi.java:1453)
	at com.intellij.ide.util.treeView.AbstractTreeUi.processExpand(AbstractTreeUi.java:4351)
	at com.intellij.ide.util.treeView.AbstractTreeUi._expand(AbstractTreeUi.java:4290)
	at com.intellij.ide.util.treeView.AbstractTreeUi$67.perform(AbstractTreeUi.java:4172)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:20)
	at com.intellij.ide.util.treeView.AbstractTreeUi.expandNext(AbstractTreeUi.java:4187)
	at com.intellij.ide.util.treeView.AbstractTreeUi$66.perform(AbstractTreeUi.java:4132)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:20)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1824)
	at com.intellij.ide.util.treeView.AbstractTreeUi.runDone(AbstractTreeUi.java:4218)
	at com.intellij.ide.util.treeView.AbstractTreeUi._expand(AbstractTreeUi.java:4114)
	at com.intellij.ide.util.treeView.AbstractTreeUi.expand(AbstractTreeUi.java:4106)
	at com.intellij.ide.util.treeView.AbstractTreeUi.expand(AbstractTreeUi.java:4101)
	at com.intellij.ide.util.treeView.AbstractTreeUi.expand(AbstractTreeUi.java:4097)
	at com.intellij.ide.util.treeView.AbstractTreeUi$28.lambda$perform$0(AbstractTreeUi.java:1542)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1803)
	at com.intellij.ide.util.treeView.AbstractTreeUi.maybeYield(AbstractTreeUi.java:1786)
	at com.intellij.ide.util.treeView.AbstractTreeUi$28.lambda$perform$1(AbstractTreeUi.java:1541)
	at com.intellij.ide.util.treeView.AbstractTreeUi.processActions(AbstractTreeUi.java:2824)
	at com.intellij.ide.util.treeView.AbstractTreeUi.processNodeActionsIfReady(AbstractTreeUi.java:2789)
	at com.intellij.ide.util.treeView.AbstractTreeUi$28.perform(AbstractTreeUi.java:1553)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:20)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1824)
	at com.intellij.ide.util.treeView.AbstractTreeUi.processUnbuilt(AbstractTreeUi.java:1506)
	at com.intellij.ide.util.treeView.AbstractTreeUi.doUpdateChildren(AbstractTreeUi.java:1237)
	at com.intellij.ide.util.treeView.AbstractTreeUi$23$1.perform(AbstractTreeUi.java:1160)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:20)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1824)
	at com.intellij.ide.util.treeView.AbstractTreeUi$23.perform(AbstractTreeUi.java:1157)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:20)
	at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:177)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.ide.util.treeView.AbstractTreeUi.updateNodeChildren(AbstractTreeUi.java:1152)
	at com.intellij.ide.util.treeView.AbstractTreeUi$45.perform(AbstractTreeUi.java:3064)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:20)
	at com.intellij.ide.util.treeView.TreeRunnable$TreeConsumer.accept(TreeRunnable.java:34)
	at org.jetbrains.concurrency.DonePromise.onSuccess(promise.kt:349)
	at org.jetbrains.concurrency.DonePromise.onSuccess(promise.kt:318)
	at com.intellij.ide.util.treeView.AbstractTreeUi.lambda$processExistingNode$11(AbstractTreeUi.java:3024)
	at org.jetbrains.concurrency.AsyncPromise$onSuccess$1.accept(AsyncPromise.kt:84)
	at org.jetbrains.concurrency.AsyncPromise$onSuccess$1.accept(AsyncPromise.kt:16)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
	at org.jetbrains.concurrency.AsyncPromise.onSuccess(AsyncPromise.kt:78)
	at org.jetbrains.concurrency.AsyncPromise.onSuccess(AsyncPromise.kt:16)
	at com.intellij.ide.util.treeView.AbstractTreeUi.processExistingNode(AbstractTreeUi.java:2968)
	at com.intellij.ide.util.treeView.AbstractTreeUi.lambda$processExistingNodes$5(AbstractTreeUi.java:1687)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1803)
	at com.intellij.ide.util.treeView.AbstractTreeUi.maybeYield(AbstractTreeUi.java:1786)
	at com.intellij.ide.util.treeView.AbstractTreeUi.lambda$processExistingNodes$6(AbstractTreeUi.java:1674)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1803)
	at com.intellij.ide.util.treeView.AbstractTreeUi.maybeYield(AbstractTreeUi.java:1786)
	at com.intellij.ide.util.treeView.AbstractTreeUi.processExistingNodes(AbstractTreeUi.java:1660)
	at com.intellij.ide.util.treeView.AbstractTreeUi.updateNodeChildrenNow(AbstractTreeUi.java:1359)
	at com.intellij.ide.util.treeView.AbstractTreeUi.doUpdateChildren(AbstractTreeUi.java:1268)
	at com.intellij.ide.util.treeView.AbstractTreeUi$23$1.perform(AbstractTreeUi.java:1160)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:20)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1824)
	at com.intellij.ide.util.treeView.AbstractTreeUi$23.perform(AbstractTreeUi.java:1157)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:20)
	at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:177)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.ide.util.treeView.AbstractTreeUi.updateNodeChildren(AbstractTreeUi.java:1152)
	at com.intellij.ide.util.treeView.AbstractTreeUi$45.perform(AbstractTreeUi.java:3064)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:20)
	at com.intellij.ide.util.treeView.TreeRunnable$TreeConsumer.accept(TreeRunnable.java:34)
	at org.jetbrains.concurrency.DonePromise.onSuccess(promise.kt:349)
	at org.jetbrains.concurrency.DonePromise.onSuccess(promise.kt:318)
	at com.intellij.ide.util.treeView.AbstractTreeUi.lambda$processExistingNode$11(AbstractTreeUi.java:3024)
	at org.jetbrains.concurrency.AsyncPromise$onSuccess$1.accept(AsyncPromise.kt:84)
	at org.jetbrains.concurrency.AsyncPromise$onSuccess$1.accept(AsyncPromise.kt:16)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
	at org.jetbrains.concurrency.AsyncPromise.onSuccess(AsyncPromise.kt:78)
	at org.jetbrains.concurrency.AsyncPromise.onSuccess(AsyncPromise.kt:16)
	at com.intellij.ide.util.treeView.AbstractTreeUi.processExistingNode(AbstractTreeUi.java:2968)
	at com.intellij.ide.util.treeView.AbstractTreeUi.lambda$processExistingNodes$5(AbstractTreeUi.java:1687)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1803)
	at com.intellij.ide.util.treeView.AbstractTreeUi.maybeYield(AbstractTreeUi.java:1786)
	at com.intellij.ide.util.treeView.AbstractTreeUi.lambda$processExistingNodes$6(AbstractTreeUi.java:1674)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1803)
	at com.intellij.ide.util.treeView.AbstractTreeUi.maybeYield(AbstractTreeUi.java:1786)
	at com.intellij.ide.util.treeView.AbstractTreeUi.processExistingNodes(AbstractTreeUi.java:1660)
	at com.intellij.ide.util.treeView.AbstractTreeUi.updateNodeChildrenNow(AbstractTreeUi.java:1359)
	at com.intellij.ide.util.treeView.AbstractTreeUi$24.perform(AbstractTreeUi.java:1261)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:20)
	at com.intellij.ide.util.treeView.TreeRunnable$TreeConsumer.accept(TreeRunnable.java:34)
	at org.jetbrains.concurrency.AsyncPromise$onSuccess$1.accept(AsyncPromise.kt:84)
	at org.jetbrains.concurrency.AsyncPromise$onSuccess$1.accept(AsyncPromise.kt:16)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
	at org.jetbrains.concurrency.AsyncPromise.onSuccess(AsyncPromise.kt:78)
	at org.jetbrains.concurrency.AsyncPromise.onSuccess(AsyncPromise.kt:16)
	at com.intellij.ide.util.treeView.AbstractTreeUi.doUpdateChildren(AbstractTreeUi.java:1257)
	at com.intellij.ide.util.treeView.AbstractTreeUi$23$1.perform(AbstractTreeUi.java:1160)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:20)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1824)
	at com.intellij.ide.util.treeView.AbstractTreeUi$23.perform(AbstractTreeUi.java:1157)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:20)
	at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:177)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.ide.util.treeView.AbstractTreeUi.updateNodeChildren(AbstractTreeUi.java:1152)
	at com.intellij.ide.util.treeView.AbstractTreeUi.updateSubtreeNow(AbstractTreeUi.java:1061)
	at com.intellij.ide.util.treeView.AbstractTreeUpdater$2.perform(AbstractTreeUpdater.java:233)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:20)
	at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:177)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.ide.util.treeView.AbstractTreeUpdater.performUpdate(AbstractTreeUpdater.java:228)
	at com.intellij.ide.util.treeView.AbstractTreeUpdater$1.run(AbstractTreeUpdater.java:204)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:333)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:323)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:273)
	at com.intellij.util.ui.EdtInvocationManager.invokeAndWaitIfNeeded(EdtInvocationManager.java:147)
	at com.intellij.util.ui.UIUtil.invokeAndWaitIfNeeded(UIUtil.java:2196)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:284)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:241)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:240)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:385)
	at com.intellij.util.Alarm$Request.run(Alarm.java:374)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1070)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:701)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:437)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1671)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1629)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:90)
	at com.jetbrains.rider.settings.RiderShowSettingsUtilImpl.showSettingsDialog(RiderShowSettingsUtilImpl.kt:51)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:50)
	at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:37)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:244)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:265)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:244)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:300)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:236)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:67)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:292)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$3(ActionMenuItem.java:131)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:131)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:541)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:571)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6419)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2790)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:757)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NoClassDefFoundError: com/jgoodies/forms/layout/FormLayout
	at com.tang.intellij.lua.project.LuaSettingsPanel.$$$setupUI$$$(LuaSettingsPanel.java)
	at com.tang.intellij.lua.project.LuaSettingsPanel.<init>(LuaSettingsPanel.java:63)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:830)
	... 240 more
Caused by: java.lang.ClassNotFoundException: com.jgoodies.forms.layout.FormLayout PluginClassLoader(plugin=PluginDescriptor(name=EmmyLua, id=com.tang, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\Rider2021.3\plugins\EmmyLua, version=1.3.6.220-IDEA213, package=null, isBundled=false), packagePrefix=null, instanceId=11, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:235)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 243 more
···

**Comment by CppCXY** [comment]
这你不得加群找阿唐，这个问题其实早就知道了，但是intellij idea没有这个问题。没研究过，可能是rider有什么问题

**Comment by RuningBun** [comment]
同一个问题+1
setting 打不开。 代码无法跳转
rider for UE 2021.3

**Comment by CppCXY** [comment]
阿唐今晚会看一下

**Comment by HungryHighness** [comment]
想问问你哪里调试器能用吗

**Comment by CppCXY** [comment]
> 想问问你哪里调试器能用吗

啥

**Comment by HungryHighness** [comment]
> > 想问问你哪里调试器能用吗
> 
> 啥
相同版本Rider2021.3.1和EmmyLua 1.3.6.220-IDEA213，现在设置界面loading倒是没什么问题，但是调试器我根据群里视频和文档走了一遍，还是Connection refused: connect，不知道现在问题出现在那里，想问问他那边能不能运行来着

**Comment by CppCXY** [comment]
> > > 想问问你哪里调试器能用吗
> > 
> > 
> > 啥
> > 版本Rider2021.3.1和EmmyLua 1.3.6.222-IDEA213，现在设置界面loading倒是没什么问题，但是调试器我根据群里视频和文档走了一遍，还是Connection refused: connect，不知道现在问题出现在那里，想问问他那边能不能运行来着

很明显你没看文档，连接失败的原因是进程 require emmy_core 失败，自己好好看你们的报错，多半是在custom loader 中错误处理了dll。如果你什么都不想改，或者不知道我在说什么，在windows10以上直接使用附加调试就好了，附加调试需要装emmylua attach插件

**Comment by HungryHighness** [comment]
> > > > 想问问你哪里调试器能用吗
> > > 
> > > 
> > > 啥
> > > 版本Rider2021.3.1和EmmyLua 1.3.6.222-IDEA213，现在设置界面loading倒是没什么问题，但是调试器我根据群里视频和文档走了一遍，还是Connection refused: connect，不知道现在问题出现在那里，想问问他那边能不能运行来着
> 
> 很明显你没看文档，连接失败的原因是进程 require emmy_core 失败，自己好好看你们的报错，多半是在custom loader 中错误处理了dll。如果你什么都不想改，或者不知道我在说什么，在windows10以上直接使用附加调试就好了，附加调试需要装emmylua attach插件

抱歉，仔细看了一下发现是自己启动顺序错了(

**Comment by tangzx** [comment]
抱歉这会才看到，还有这个问题？
