### ISSUE TITLE
Indexing is stuck

### ISSUE THREAD

**Issue by SLukashenko** [EmmyLua/IntelliJ-EmmyLua#459]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version         build #IU-213.6777.52, 27 Jan 2022 22:53
 EmmyLua version | EmmyLua (1.3.6.222-IDEA213)
 OS                       OS: Windows 10 (10.0, amd64) 

What are the steps to reproduce this issue?（重现步骤？）
------------------------------------------------
1. …
2. …
3. …

What happens?（出现什么问题？）
Indexing never finishes and locks UI

…

What were you expecting to happen?（期望？）
-----------------------------------------
…

Any logs, error output, etc?（有没有什么log, error输出？）
------------------------------

"AWT-EventQueue-0" prio=0 tid=0x0 nid=0x0 waiting on condition
     java.lang.Thread.State: TIMED_WAITING  on com.intellij.openapi.application.impl.ReadMostlyRWLock@5966f5eb

	at java.base@11.0.13/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.13/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.writeLock(ReadMostlyRWLock.java:237)
	at com.intellij.openapi.application.impl.ApplicationImpl.startWrite(ApplicationImpl.java:1142)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:933)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:956)

"Indexing" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE

	at com.tang.intellij.lua.ty.Ty.<clinit>(Ty.kt:198)
	at com.tang.intellij.lua.comment.psi.LuaDocPsiImplUtilKt.resolveType(LuaDocPsiImplUtil.kt:53)
	at com.tang.intellij.lua.comment.psi.LuaDocPsiImplUtilKt.getType(LuaDocPsiImplUtil.kt:252)
	at com.tang.intellij.lua.comment.psi.impl.LuaDocGeneralTyImpl.getType(LuaDocGeneralTyImpl.java:38)
	at com.tang.intellij.lua.comment.psi.LuaDocPsiImplUtilKt.getType(LuaDocPsiImplUtil.kt:150)
	at com.tang.intellij.lua.comment.psi.impl.LuaDocTagReturnImpl.getType(LuaDocTagReturnImpl.java:51)
	at com.tang.intellij.lua.stubs.LuaFuncType.createStub(LuaFuncStub.kt:47)
	at com.tang.intellij.lua.stubs.LuaFuncType.createStub(LuaFuncStub.kt:36)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.createStub(DefaultStubBuilder.java:85)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.visitNode(DefaultStubBuilder.java:60)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.buildStubTree(DefaultStubBuilder.java:55)

Any other comments?（其它说明）
https://youtrack.jetbrains.com/issue/IDEA-288739

**Comment by kom0055** [comment]
雀食，我的idea加载卡住了，好蛋疼，转战vs code

**Comment by kom0055** [comment]
老哥如果修复了 记得戳我啊

**Comment by CppCXY** [comment]
卡加载是因为emmylua的一万个bug，通常需要删除插件重建索引，索引建完之后再装插件，或者尝试从ci上下载新版本，看有没有解决这个问题

**Comment by macks2008** [comment]
I am wondering if this is why I keep crashing when the plugin is enabled. I have a very similar thread dump in my logging folder. I think it's interesting that IDEA is smart enough to detect that it was frozen and name the subfolder "threadDumps-freeze-<date stamp>"...

**Comment by macks2008** [comment]
Also, what do you mean about rebuilding the index @CppCXY ? Google translate did a pretty good job, but I do not fully understand.

**Comment by CppCXY** [comment]
> Also, what do you mean about rebuilding the index @CppCXY ? Google translate did a pretty good job, but I do not fully understand.


File > Invalid Caches。

Remove the plugin before that，and reinstall after indexing complete
