### ISSUE TITLE
Crash start the intelliJ IDE CE - Version ideaIC-231.9011.4-aarch64

### ISSUE THREAD

**Issue by KoiKoi2000** [EmmyLua/IntelliJ-EmmyLua#539]
On open  ideaIC-231.9011.4-aarch64 intelliJ IDE CE:

Internal error. Please refer to https://jb.gg/ide/critical-startup-errors

com.intellij.diagnostic.PluginException: Key com.tang.intellij.lua.project.LuaSettings duplicated; existingAdapter: ServiceAdapter(descriptor=ServiceDescriptor(interface='null', serviceImplementation='com.tang.intellij.lua.project.LuaSettings', testServiceImplementation='null', headlessImplementation='null', overrides=false, configurationSchemaKey='null', preload=FALSE, client=null), pluginDescriptor=PluginDescriptor(name=Luanalysis, id=au.com.glassechidna.luanalysis, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IdeaIC2023.1/plugins/Luanalysis, version=1.4.0, package=null, isBundled=false)); descriptor: com.tang.intellij.lua.project.LuaSettings; app: Application (containerState PRE_INIT) ; current plugin: com.tang
    at com.intellij.serviceContainer.ComponentManagerImpl.registerServices(ComponentManagerImpl.kt:588)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:293)
    at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:46)
    at com.intellij.idea.ApplicationLoader.doInitApplication(ApplicationLoader.kt:86)
    at com.intellij.idea.ApplicationLoader.access$doInitApplication(ApplicationLoader.kt:1)
    at com.intellij.idea.ApplicationLoader$doInitApplication$1.invokeSuspend(ApplicationLoader.kt)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
    at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
    at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
    at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:63)
    at com.D.K.D.E.r.o(r.java:56)
    at com.D.K.D.E.Dr.o(Dr.java:110)
    at com.D.K.D.E.DU.D(DU.java:137)
    at com.D.K.D.E.Du.D(Du.java:53)
    at com.intellij.idea.MainImpl.start(MainImpl.kt:12)
    at com.intellij.idea.StartupUtil$startApplication$7.invokeSuspend(StartupUtil.kt:297)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
    at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
    at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
    at com.intellij.idea.Main.main(Main.kt:40)

-----
Your JRE: 17.0.6+10-b829.9 aarch64 (JetBrains s.r.o.)
/Applications/IntelliJ IDEA CE.app/Contents/jbr/Contents/Home

**Comment by CppCXY** [comment]
please go back to 2022.3

**Comment by tangzx** [comment]
you can't install EmmyLua and Luanalysis in same time, Luanalysis is a branch of EmmyLua, so they're going to conflict on some configuration
