### ISSUE TITLE
Crashes on CLion 2023.3.2

### ISSUE THREAD

**Issue by stustd** [EmmyLua/IntelliJ-EmmyLua#574]
Environment（环境）
--------------
   name   |   version  
----------|----------
 IDEA version          | CL2023.3.2
 EmmyLua version | 1.4.[9-11]-IDEA231
 OS                            | Linux/Ubuntu-22.04]
------------------------------------------------

Latest non-crashing version: 1.4.7-IDEA231

**Comment by CppCXY** [comment]
try File> Invalid Caches

**Comment by stustd** [comment]
> try File> Invalid Caches

No difference. Here's what Java throws:
```
stustd@ax010:[AxLuaLib]: /home/stustd/.local/share/JetBrains/Toolbox/apps/clion/bin/clion.sh 
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true
WARN: id redefinition ([row,col {unknown-source}]: [19,5])

Start Failed
Internal error. Please refer to https://jb.gg/ide/critical-startup-errors

java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.application.Application.getService(java.lang.Class)" because the return value of "com.intellij.openapi.application.ApplicationManager.getApplication()" is null
	at com.intellij.internal.statistic.eventLog.StatisticsEventLogProviderUtil.getEventLogProvider(StatisticsEventLogProviderUtil.kt:15)
	at com.intellij.internal.statistic.eventLog.events.BaseEventId.getLogger$intellij_platform_statistics(EventId.kt:14)
	at com.intellij.internal.statistic.eventLog.events.EventId1.log(EventId.kt:46)
	at com.intellij.ide.T.x.n.T(n.java:202)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.intellij.idea.E.invokeSuspend(E.java:59)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.intellij.idea.E.T(E.java)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.intellij.idea.E.invoke(E.java)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.intellij.idea.MainImpl.start(MainImpl.kt:58)
	at com.intellij.platform.ide.bootstrap.StartupUtil$startApplication$8$2.invokeSuspend(main.kt:346)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.intellij.idea.Main.mainImpl(Main.kt:63)
	at com.intellij.idea.Main.mainImpl$default(Main.kt:49)
	at com.intellij.idea.Main.main(Main.kt:46)
	Suppressed: com.intellij.diagnostic.PluginException: com.tang.intellij.lua.project.LuaSettings [Plugin: au.com.glassechidna.luanalysis]
		at com.intellij.serviceContainer.ComponentManagerImpl.registerServices2(ComponentManagerImpl.kt:854)
		at com.intellij.serviceContainer.ComponentManagerImpl.registerServices(ComponentManagerImpl.kt:806)
		at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:403)
		at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:58)
		at com.intellij.platform.ide.bootstrap.ApplicationLoader$initServiceContainer$2.invokeSuspend(ApplicationLoader.kt:197)
		at com.intellij.platform.ide.bootstrap.ApplicationLoader$initServiceContainer$2.invoke(ApplicationLoader.kt)
		at com.intellij.platform.ide.bootstrap.ApplicationLoader$initServiceContainer$2.invoke(ApplicationLoader.kt)
		at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
		at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
		at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
		at com.intellij.platform.diagnostic.telemetry.impl.TracerKt.span(tracer.kt:56)
		at com.intellij.platform.diagnostic.telemetry.impl.TracerKt.span$default(tracer.kt:49)
		at com.intellij.platform.ide.bootstrap.ApplicationLoader.initServiceContainer(ApplicationLoader.kt:196)
		at com.intellij.platform.ide.bootstrap.ApplicationLoader.access$initServiceContainer(ApplicationLoader.kt:1)
		at com.intellij.platform.ide.bootstrap.ApplicationLoader$loadApp$2$initServiceContainerJob$1.invokeSuspend(ApplicationLoader.kt:86)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
		at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Caused by: com.intellij.platform.instanceContainer.internal.InstanceAlreadyRegisteredException: com.tang.intellij.lua.project.LuaSettings
		at com.intellij.platform.instanceContainer.internal.InstanceRegistrarImpl.registerInitializer(InstanceRegistrarImpl.kt:32)
		at com.intellij.serviceContainer.ComponentManagerImpl.registerServices2Inner(ComponentManagerImpl.kt:910)
		at com.intellij.serviceContainer.ComponentManagerImpl.registerServices2(ComponentManagerImpl.kt:847)
		... 20 more

-----
Your JRE: 17.0.9+7-b1087.9 amd64 (JetBrains s.r.o.)
/home/stustd/.local/share/JetBrains/Toolbox/apps/clion/jbr
```
With 
```
CLion 2023.3.2
Build #CL-233.13135.93, built on December 19, 2023
Licensed to Stu Stannard
Subscription is active until February 26, 2024.
Runtime version: 17.0.9+7-b1087.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.5.0-14-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 4086M
Cores: 16
Registry:
  debugger.new.tool.window.layout=true
  debugger.attach.dialog.enabled=true
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
Non-Bundled Plugins:
  cc.duduhuo.git-conflict (1.0.5)
  emacsIDEAs (1.4.9)
  com.datagraph (1.1.0-233)
  com.dmitryzhelnin.intellij.plugin.gitextensions (0.4.4)
  com.cursive-ide.emacsplus (0.3.900)
  org.eightnineplugins.XMLExtractor (1.0.1)
  org.jetbrains.action-tracker (0.3.3)
  com.andrewbrookins.wrap_to_column (1.8.0)
  commit-template-idea-plugin (1.2.0)
  com.andrey4623.rainbowcsv (2.0.2)
  com.intellij.plugins.emacskeymap (231.7515.9)
  com.gitlab.lae.intellij.actions.tree (0.6.2)
  com.vecheslav.darculaDarkerTheme (1.2.0)
  com.corochann.plugin.clion.singlefileexecutionplugin (1.3)
  au.com.glassechidna.luanalysis (1.4.0)
  indent-rainbow.indent-rainbow (2.1.0)
  com.napalmpapalam.napalmpapalam.theme (1.0.1)
  com.samdark.intellij-visual-studio-code-dark-plus (2.8)
  PlantUML integration (6.1.0-IJ2022.2)
  io.xmake (1.2.3)
  com.zero9178 (1.1.3)
  n.v.k.Qt6Renderer (1.0.0)
  com.mrarm.coffeebean.ui.theme (1.0.1)
  izhangzhihao.rainbow.brackets (2023.3.9-233)
  uk.co.ben-gibson.remote.repository.mapper (4.3.5)
  com.ppolivka.plugin.gitcleaner (1.1.4)
  pers.tommas.emacsflavor (1.2-SNAPSHOT)
Current Desktop: MATE
```

**Comment by CppCXY** [comment]
you've installed luaanalysis, which is emmylua's fork that doesn't work together.
